//! TmuxCtl — the ONLY place zeromux builds tmux command lines.
//!
//! Invariants (see docs/superpowers/specs/2026-09-26-tmux-default-terminal-design.md):
//! - every command carries `-N` so zeromux can never start a tmux server inside
//!   its own cgroup (it would die on `systemctl stop zeromux`); only
//!   zeromux-tmux.service starts the server.
//! - targets are always `=name` exact matches (tmux otherwise prefix-matches).
//! - argv only, never a shell; 3s timeout per command.

use std::path::{Path, PathBuf};
use std::time::Duration;

const TIMEOUT: Duration = Duration::from_secs(3);
pub const TMUX_CONF_VERSION: u32 = 1;

#[derive(Debug, Clone, PartialEq)]
pub enum TmuxError { ServerDown, NotFound, Timeout, Other(String) }

impl std::fmt::Display for TmuxError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            TmuxError::ServerDown => write!(f, "tmux 服务未运行（zeromux-tmux.service）"),
            TmuxError::NotFound => write!(f, "tmux 会话不存在"),
            TmuxError::Timeout => write!(f, "tmux 命令超时"),
            TmuxError::Other(s) => write!(f, "tmux: {s}"),
        }
    }
}

#[derive(Debug, Clone, serde::Serialize)]
pub struct TmuxHealth { pub server: bool, pub in_unit: bool }

#[derive(Debug, Clone)]
pub struct TmuxCtl { socket: Option<String> }

impl TmuxCtl {
    pub fn new(socket: Option<String>) -> Self {
        Self { socket: socket.filter(|s| !s.is_empty()) }
    }

    pub fn base_args(&self) -> Vec<String> {
        match &self.socket {
            Some(s) => vec!["-L".into(), s.clone(), "-N".into()],
            None => vec!["-N".into()],
        }
    }

    pub async fn run(&self, args: &[&str]) -> Result<String, TmuxError> {
        let mut cmd = tokio::process::Command::new("tmux");
        cmd.args(self.base_args()).args(args).env_remove("TMUX").kill_on_drop(true);
        let out = tokio::time::timeout(TIMEOUT, cmd.output())
            .await
            .map_err(|_| TmuxError::Timeout)?
            .map_err(|e| TmuxError::Other(e.to_string()))?;
        if out.status.success() {
            return Ok(String::from_utf8_lossy(&out.stdout).into_owned());
        }
        Err(classify_stderr(&String::from_utf8_lossy(&out.stderr)))
    }

    pub async fn health(&self) -> TmuxHealth {
        let pid = match self.run(&["display-message", "-p", "#{pid}"]).await {
            Ok(s) => s.trim().to_string(),
            Err(_) => return TmuxHealth { server: false, in_unit: false },
        };
        let cg = std::fs::read_to_string(format!("/proc/{pid}/cgroup")).unwrap_or_default();
        TmuxHealth { server: true, in_unit: cg.contains("zeromux-tmux.service") }
    }
}

fn classify_stderr(err: &str) -> TmuxError {
    if err.contains("error connecting to") || err.contains("no server running") {
        TmuxError::ServerDown
    } else if err.contains("can't find session") || err.contains("can't find pane")
        || err.contains("can't find window") || err.contains("session not found")
        || err.contains("no sessions") {
        TmuxError::NotFound
    } else {
        TmuxError::Other(err.trim().to_string())
    }
}

pub fn tmux_conf_text() -> String {
    format!(
"# zeromux-tmux-conf v{TMUX_CONF_VERSION} — generated by zeromux; edits are overwritten on upgrade.
source-file -q ~/.tmux.conf
set -g exit-empty off
set -g history-limit 50000
set -g mouse on
set -sg escape-time 10
set -g default-terminal tmux-256color
set -as terminal-features ',xterm-256color:RGB'
set -g set-clipboard on
set -g focus-events on
set -g window-size latest
set -g status-left ''
set -g status-right ''
set -g status-style 'bg=default'
")
}

/// Write `<data_dir>/tmux.conf` if missing or from an older version.
pub fn write_tmux_conf(data_dir: &Path) -> std::io::Result<PathBuf> {
    let p = data_dir.join("tmux.conf");
    let want = tmux_conf_text();
    if std::fs::read_to_string(&p).ok().as_deref() != Some(want.as_str()) {
        std::fs::create_dir_all(data_dir)?;
        std::fs::write(&p, want)?;
    }
    Ok(p)
}

#[cfg(test)]
pub(crate) mod tests {
    use super::*;
    use std::sync::atomic::{AtomicUsize, Ordering};

    static N: AtomicUsize = AtomicUsize::new(0);

    /// Isolated tmux server on a private socket. Killed on drop.
    pub(crate) struct TestServer { pub ctl: TmuxCtl, pub socket: String }
    impl TestServer {
        pub(crate) fn start() -> Option<Self> {
            if std::process::Command::new("tmux").arg("-V").output().is_err() { return None; }
            let socket = format!("zmx-test-{}-{}", std::process::id(), N.fetch_add(1, Ordering::SeqCst));
            // Boot the server (tests are the only place allowed to start one without -N).
            let ok = std::process::Command::new("tmux")
                .args(["-L", &socket, "-f", "/dev/null", "new-session", "-d", "-s", "boot"])
                .status().map(|s| s.success()).unwrap_or(false);
            if !ok { return None; }
            let _ = std::process::Command::new("tmux")
                .args(["-L", &socket, "set", "-g", "exit-empty", "off"]).status();
            Some(Self { ctl: TmuxCtl::new(Some(socket.clone())), socket })
        }
    }
    impl Drop for TestServer {
        fn drop(&mut self) {
            let _ = std::process::Command::new("tmux").args(["-L", &self.socket, "kill-server"]).status();
        }
    }

    #[test]
    fn base_args_always_has_no_start_flag() {
        assert_eq!(TmuxCtl::new(None).base_args(), vec!["-N"]);
        assert_eq!(TmuxCtl::new(Some("s".into())).base_args(), vec!["-L", "s", "-N"]);
    }

    #[test]
    fn conf_sources_user_conf_first_and_pins_options() {
        let t = tmux_conf_text();
        let first = t.lines().find(|l| !l.starts_with('#')).unwrap();
        assert_eq!(first, "source-file -q ~/.tmux.conf");
        for opt in ["exit-empty off", "history-limit 50000", "mouse on", "window-size latest", "set-clipboard on"] {
            assert!(t.contains(opt), "missing {opt}");
        }
        assert!(t.contains(&format!("zeromux-tmux-conf v{}", TMUX_CONF_VERSION)));
    }

    #[test]
    fn write_conf_is_idempotent_and_upgrades_old_version() {
        let d = tempfile::tempdir().unwrap();
        let p = write_tmux_conf(d.path()).unwrap();
        assert_eq!(std::fs::read_to_string(&p).unwrap(), tmux_conf_text());
        std::fs::write(&p, "# zeromux-tmux-conf v0\n").unwrap();
        write_tmux_conf(d.path()).unwrap();
        assert_eq!(std::fs::read_to_string(&p).unwrap(), tmux_conf_text());
    }

    #[tokio::test]
    async fn run_without_server_is_server_down_not_autostart() {
        let ctl = TmuxCtl::new(Some(format!("zmx-test-none-{}", std::process::id())));
        match ctl.run(&["list-sessions"]).await {
            Err(TmuxError::ServerDown) => {}
            other => panic!("expected ServerDown, got {other:?}"),
        }
        let h = ctl.health().await;
        assert!(!h.server && !h.in_unit);
    }

    #[tokio::test]
    async fn health_up_but_not_in_unit_for_test_server() {
        let Some(srv) = TestServer::start() else { return };
        let h = srv.ctl.health().await;
        assert!(h.server);
        assert!(!h.in_unit);
    }
}
